/**
 * About page.
 *
 * Who built the site and why — from public display metadata
 * (config/site.js) with neutral fallbacks. Nothing personal is invented:
 * any value not supplied through environment configuration renders as an
 * explicitly documented placeholder. No analytical content lives here.
 *
 * Freshness model: the site update date is a manual developer date (never
 * data-driven). The reference data vintage is an explicit developer
 * override when fully configured, otherwise the live upstream WDI vintage
 * from the backend (automatic mode); a partial override is invalid and
 * falls back to automatic with a diagnostic warning.
 */

import { useEffect } from 'react';
import { api } from '../api/client.js';
import { useApi } from '../hooks/useApi.js';
import { formatVintageMonth } from '../utils/format.js';
import { Section } from '../components/ui.jsx';

export default function About({ site, onOpenView }) {
  const authorLine = site?.authorSpecified
    ? [site.authorName, site.authorRole].filter(Boolean).join(' · ')
    : 'Author details not specified in this deployment.';
  const hasOverride = site?.dataYear != null && site?.dataMonth != null;
  const hasPartialOverride =
    !hasOverride && (site?.dataYear != null || site?.dataMonth != null);
  useEffect(() => {
    if (hasPartialOverride) {
      console.warn(
        'About: incomplete VITE_SITE_DATA_* override (year or month missing); using the automatic reference vintage instead.',
      );
    }
  }, [hasPartialOverride]);
  // Automatic mode reads the authoritative upstream vintage at runtime, so
  // a newer WDI release appears without rebuilding the frontend. Skipped
  // entirely under an explicit override; failures keep the neutral fallback.
  const { data } = useApi((signal) => api.dataStatus({ signal }), 'about:vintage', {
    enabled: !hasOverride,
  });
  const autoVintage = !hasOverride ? formatVintageMonth(data?.wbLastUpdated) : null;
  const vintageText = hasOverride ? site?.dataText : (autoVintage ?? 'See Status for live vintage');
  return (
    <div role="tabpanel" id="panel-about" aria-labelledby="tab-about">
      <Section
        id="about-project"
        title="About this site"
        subtitle="Structured, quality analysis directly over World Bank raw data."
      >
        <div className="insight" aria-label="Project motivation">
          <h3>Why this exists</h3>
          <p>
            Public economic data is easy to quote and hard to verify. This project exists to close
            that gap for one dataset: every figure it shows is derived, reproducibly, from World
            Bank World Development Indicators raw observations — with the method for each analysis
            published alongside the result, and missing data shown as missing instead of being
            silently filled in.
          </p>
          <p>
            Rankings and calculations are generated by the project&apos;s documented analytical
            methodology. They are never manually entered, and the World Bank does not publish
            the rank values shown here.
          </p>
        </div>
        <dl className="facts facts-grid">
          <div>
            <dt>Developed by</dt>
            <dd>{authorLine}</dd>
          </div>
          <div>
            <dt>Site update date</dt>
            <dd>{site?.lastUpdatedText ?? 'Update date not specified'}</dd>
          </div>
          <div>
            <dt>Reference data vintage</dt>
            <dd>{vintageText}</dd>
          </div>
          <div>
            <dt>Source dataset</dt>
            <dd>{site?.sourceName ?? 'World Bank WDI'}</dd>
          </div>
        </dl>
        <p className="footnote">
          The site update date above is the date of the site&apos;s own most recent
          product/content update. The reference vintage names the World Bank WDI data
          release represented here. The authoritative data vintage,
          latest available year and dataset freshness always come from the backend — see Status.
        </p>
        <div className="analysis-header-side">
          <button type="button" className="btn btn-secondary" onClick={() => onOpenView?.('methodology')}>
            How calculations work
          </button>
          <button type="button" className="btn btn-secondary" onClick={() => onOpenView?.('status')}>
            Check data status
          </button>
        </div>
      </Section>
      <Section
        id="about-contact"
        title="Contact"
        subtitle="Questions, feedback, or issues related to the site."
      >
        <p>
          For questions, feedback, or issues related to the site — the data, the methods, or how
          results are presented — contact the project at the address below.
        </p>
        {site?.contactSpecified ? (
          <p>
            <a className="btn btn-secondary contact-email" href={`mailto:${site.contactEmail}`}>
              {site.contactEmail}
            </a>
          </p>
        ) : (
          <p className="status status-empty" role="status">
            Contact details have not been published for this deployment.
          </p>
        )}
        <p className="footnote">
          The address above is public display metadata, not a credential. Never send passwords,
          tokens, or other secrets by email.
        </p>
      </Section>
      <details id="about-resilience" className="details resilience-disclosure">
        <summary>How the site stays available</summary>
        <div className="resilience-body">
          <p className="resilience-lead">
            The site normally runs on its primary data service, which holds the dataset behind
            every analysis.
          </p>
          <h4>During a temporary interruption</h4>
          <p>
            If that service is temporarily unavailable, the application can use a locally kept
            backup copy when one is available. This helps keep the site available and previously
            published data accessible, rather than leaving the site with nothing to show during
            the interruption.
          </p>
          <h4>Keeping the data current</h4>
          <p>
            The backup is not simply a frozen copy. While it is active, the site keeps working
            the same way, and when the stored data becomes due for an update, the site can
            refresh it through its normal refresh cycle — being on the backup does not mean the
            site is stuck with old data until the primary service returns.
          </p>
          <p>
            The site is also designed to avoid unnecessary data work, both when serving analysis
            and when refreshing data. Information that has not changed is left alone, while only
            what needs updating is processed. This helps the backup continue serving analysis
            and handling refreshes efficiently while the primary service is unavailable.
          </p>
          <h4>Returning to the primary service</h4>
          <p>
            Starting up or returning to normal may take a little longer while the backup is
            prepared or the primary service is checked again. Once the primary service is
            available, the application can return to it through its normal guarded recovery. You
            can always see which data source is currently active on the Status page,
            next to “Database”.
          </p>
        </div>
      </details>
    </div>
  );
}
